### PR TITLE
Added docker testcase for docker exec in T1609.yaml

### PR DESCRIPTION
**Pull request by aman143kri**
Fairly straight forward way to execute into a container.

**Details:**
The test was created for Kubernetes and mitre framework also mentioned docker. So created a second test for the same.

**Testing:**
Tested using ubuntu as the base image. If using just Docker, run the container(already present in the script) and execute the test case.

It may take up to a minute to run due to image creation. If it hangs for longer than a minute, something went wrong.

**Associated Issues:**
None

### CODE REVIEW

**Comment by aman143kri** [comment]
Execution Screenshot

image

**Comment by patel-bhavin** [comment]
@aman143kri : While testing this atomic, i noticed the build path. can you update the path to a relative path? see screenshot! 
Also, can you add some reference links in the description as to where have you seen this atomic used in the wild?  That will be awesome for our community!  Thank you for this PR

image

**Comment by aman143kri** [comment]
Hey, Thanks for the feedback. I have made all the asked changes. Please let me know if any other changes are needed.

**Review by patel-bhavin — APPROVED** [review]
Looks good! thanks.

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
