### PR TITLE
Add AWS platform to appropriate tests

### PR DESCRIPTION
**Pull request by tvjust**
**Details:**

Adjusting the platforms on these tests to match what they're actually testing. 
**Testing:**

No changes made to the execution portions. 

**Associated Issues:**

### CODE REVIEW

**Comment by patel-bhavin** [comment]
Hello @tvjust : Thank you for the PR. Can you undo the changes in the .md files? those files are automatically generated from the yaml files. 
The yaml changes look good!

**Comment by tvjust** [comment]
My bad, just removed the .md edits. Thanks for the review!

**Review by clr2of8 — APPROVED** [review]

**Comment by clr2of8** [comment]
@patel-bhavin It is ok to leave the md changes as long as everyone is aware that nothing in them will persist after the merge because they will be rebuilt from the yaml source.

**Comment by patel-bhavin** [comment]
thats correct! it didnt occur to me that the PR is still valid. Thank you for the approval!

**Pull request merged**
