### PR TITLE
Added Injection SID-History with mimikatz

### PR DESCRIPTION
**Pull request by Rich5**
**Details:**
Added test to inject into SID History using mimikatz

**Testing:**
Tested locally.

**Associated Issues:**
N/A

### CODE REVIEW

**Review by clr2of8 — APPROVED** [review]
Impressive, first-time contribution has prereqs, cleanup commands and input args! Does this technique really not require admin?

**Comment by Rich5** [comment]
Oh good catch. It does require admin. I'm still getting the hang of the framework. Sorry about that. Do I just change elevation_required to true?

**Review by clr2of8 — APPROVED** [review]
yep, that's it

**Comment by Rich5** [comment]
Changed.

**Pull request merged**
