### PR TITLE
T1547.001 Fix test a70faea1-e206-4f6f-8d9a-67379be8f6f1

### PR DESCRIPTION
**Pull request by frack113**
**Details:**
Test a70faea1-e206-4f6f-8d9a-67379be8f6f1 and b5c9a9bc-dda3-4ea0-b16a-add8e81ab75f are the same
test fail if "HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run" did not exist

**Testing:**
Windows 10 

**Associated Issues:**
None

### CODE REVIEW

**Review by clr2of8 — CHANGES_REQUESTED** [review]
Did you mean to delete the second test? It sounded like you meant to just add the "check if key exists" check to both atomics. Can you double check?

**Comment by frack113** [comment]
My bad  , one is for HKCU the other for HKLM .
I remove the second by  @mistake.
Will fix ASAP

**Comment by frack113** [comment]
Fix the 2 tests the same way

**Review by clr2of8 — APPROVED** [review]
🥇

**Pull request merged**
