### PR TITLE
T1136.001 new atomics

### PR DESCRIPTION
**Pull request by P4T12ICK**
**Details:**
New atomic for T1136.001. This will create a new local admin account.

**Testing:**
Screenshot 2020-07-08 at 13 25 15

**Associated Issues:**

### CODE REVIEW

**Comment by clr2of8** [comment]
Bummer, there is something odd about GitHub and your Pull Requests for some reason and it won't let me update and merge. I can't figure out what is different here.

**Comment by clr2of8** [comment]
When you do a PR, do you select (or leave selected) the option that says "let maintainers modify this PR"?

**Comment by clr2of8** [comment]
Also, have you joined the Atomic Red Team slack workspace? I'd love to chat interactively over there with you if possible. thx

**Comment by P4T12ICK** [comment]
Hi Carrie, I will do the changes next week and update it. I hope that is okay. I will join the the Atomic Red Team Slack workspace.

**Pull request merged**
