### PR TITLE
Adding changes to address #1141 new feature request

### PR DESCRIPTION
**Pull request by xenoscr**
**Details:**
I did my best to duplicate the example from @MHaggis' comment in the new feature request #1141. The changes include:

- The scoring has been changed from static 0 or 100 to indicate the total number of tests per technique.
- The parent technique contains a total including sub-technique totals.
- The gradient has updated to provide 5 levels of color to represent 0 to 100.
- A new method "update_techniquesList" was added to simplify/reduce code repetition when updating each techniques list.
- The legend was updated to reflect the new color gradients.

**Testing:**
I ran the script and did some spot checking of each of the generated layers. Totals and values appear to be correct.

**Associated Issues:**
#1141

### CODE REVIEW

**Review by clr2of8 — CHANGES_REQUESTED** [review]
This is cool, good job, and I'm sorry I messed up your PR. The JSON files don't need to be included with the PR because they are build by the generate docs script. I tried to remove them because they were causing conflicts that I didn't want to resolve because they would resolve themselves when built again. But I'm afraid I set the files to be deleted instead of just ignored.

Other than that, I would just like to have the color coding scale changed to the following 10+,7,4,2,1. Could you make those changes and submit the PR with only the generate-atomics-docs.rb as part of the PR? Thx!

**Comment by xenoscr** [comment]
> This is cool, good job, and I'm sorry I messed up your PR. The JSON files don't need to be included with the PR because they are build by the generate docs script. I tried to remove them because they were causing conflicts that I didn't want to resolve because they would resolve themselves when built again. But I'm afraid I set the files to be deleted instead of just ignored.
> 
> Other than that, I would just like to have the color coding scale changed to the following 10+,7,4,2,1. Could you make those changes and submit the PR with only the generate-atomics-docs.rb as part of the PR? Thx!

Sure thing, I will get to this in a few hours. Sorry for the trouble with the JSON files.

**Comment by xenoscr** [comment]
@clr2of8 it took some jiggering but I rebased, removed the JSON changes, and updated the generator with changes that I hope are satisfactory. I changed the color gradient back to two colors and set the min value to 0, and max to 10. The result is that the ATT&CK Navigator selects an appropriate grade for values between 0 and 10, anything above 10 is the max color.

**Comment by clr2of8** [comment]
ah, that is super cool!

**Review by clr2of8 — APPROVED** [review]
Let's give it a go! Thx! 💯

**Comment by xenoscr** [comment]
No trouble at all. Setting my sights on an interesting challenge in the Invoke-AtomicRedTeam repo next.

⁣Conor

On Aug 24, 2022, 18:35, at 18:35, Carrie Roberts ***@***.***> wrote:
***@***.*** approved this pull request.
>
>Let's give it a go! Thx! 💯 
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/redcanaryco/atomic-red-team/pull/2093#pullrequestreview-1084584236
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Pull request merged**
