### PR TITLE
Added a new atomic related to adding permission to the application. 

### PR DESCRIPTION
**Pull request by WojciechLesicki**
**Details:**
This atomic is intended to help verify in case an application in AzureAD receives new permissions. These permission can be used by the threat actor for persistence, privilege escalation in AzureAD itself or further operation in the attacked infrastructure.

I was inspired by the materials prepared by Matt Zorich (@reprise99) and Andy Robbins (@andyrobbins).
I also used part of the powershell code created by Morgan Tech Space:
https://morgantechspace.com/2021/03/create-and-configure-azure-ad-application-using-powershell.html

**Testing:**
I tested this atomic in my own Azure tenant.

### CODE REVIEW

**Comment by MarrelleBailey** [comment]
@WojciechLesicki doing awesome with the contributions!!

**Comment by WojciechLesicki** [comment]
@patel-bhavin nice to working with you again :) 
I added this atomic again to the T1098. So far, I don't see a better technique for this.

@MarrelleBailey thanks! :)

**Comment by patel-bhavin** [comment]
@WojciechLesicki : yes :)  T1098 does seem like the closest technique we can map this atomic to. 
 A few things:
 - update atomic name to `AzureAD - Adding permission to application
 - the description seems incomplete. Can we also add links in the description of the atomic to relevant articles that explain this TTP better?
 - can you also provide a screenshot of the execution? that'll be super helpful.

**Comment by WojciechLesicki** [comment]
Thanks @patel-bhavin for review :)

1. Name - done
2. Thanks for finding this mistake with description, I forgot to copy it. I also added links there, I thought about it myself. As you say, the more knowledge the better, but I was wondering if this form is the best. Thanks for your confirmation.
3. Hmm here in PR?
4. Done, but confirm if that's what you mean ;)

**Comment by patel-bhavin** [comment]
Thanks for the updates. .yes, please add a screenshot in this PR.
the md files are automatically generated by a script in atomic red team, so you dont have to manually add it to a PR

**Comment by patel-bhavin** [comment]
thanks for updating the requested changes and screenshoot! the atomic looks good now :)

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
