### PR TITLE
Terraform Proposal

### PR DESCRIPTION
**Pull request by cyberbuff**
**Details:**

Cloud Atomics might require additional resources to be deployed as prerequisites for successful execution. Right now, the atomics use the default CLI version to create and delete resources. We can use terraform as a standard to spin up new resources and tear down them. The executors (like Invoke-Atomic) can run `terraform apply` in the before execution and `terraform destroy` after execution. 

**Future Enhancements:**
- Terraform Outputs can be used in AtomicTestHarnesses to detect whether the tests have been successfully executed.

### CODE REVIEW

**Comment by rc-joshrickard** [comment]
If I am following this correctly, I think this is a good idea but ultimately I believe these are dependencies and should be treated as inputs instead of their own entity within the yaml definition. 

I also think that keeping these files as self-contained as possible is ideal for everyone. Having the `terraform` formatted as dependencies is a better approach instead of having logic that is different for specific tests vs. using a common framework.

That being said, it may beneficial to look at the yaml definitions holistically and also re-evaluate the yaml which should ultimate result in a defined JSON Schema (made this previously - historical more than actual https://github.com/redcanaryco/atomic-red-team/pull/1619)

**Comment by cyberbuff** [comment]
Hello @rc-joshrickard. Sorry for the late reply. I agree with you about being terraform as dependencies. The names of the resources should still be input arguments and exported as terraform variables so that the executors can change resource names at runtime. I have a couple questions as well. We can discuss more about this over Slack.

**Review by patel-bhavin — APPROVED** [review]

**Comment by patel-bhavin** [comment]
@cyberbuff : Thank you so much for spending time on this new and slick feature and for your patience! I believe this introduces a really nice flavor of writing and thinking of attacks in cloud.

We will do a more formal announcement from Atomic Red team side in the next few weeks!!!

**Comment by cyberbuff** [comment]
Thanks @patel-bhavin and @clr2of8 for all the help. Happy to contribute and give back to the community.

**Pull request merged**
