### PR TITLE
Update T1120.yaml

### PR DESCRIPTION
**Pull request by collinmsec**
Added fsutil drive discovery for the technique of Peripheral Device Discovery

**Details:**

**Testing:**

**Associated Issues:**

### CODE REVIEW

**Comment by collinmsec** [comment]
Not sure if this filled out properly so commenting here: 

Added fsutil drive discovery for the technique of Peripheral Device Discovery

Details:
Added fsutil fsinfo drives as a means for Peripheral Device Discovery

Testing:
Tested locally on windows device via non elevated command prompt.

Associated Issues:
No issues

**Comment by collinmsec** [comment]
Made changes due to errors in the workflow

**Comment by collinmsec** [comment]
Apologies, made a few more changes! First timer (: Hopefully should make it through the workflow checks now

**Review by clr2of8 — APPROVED** [review]
Thank you for your first-time contribution. Keep it up! Don't forget to claim your free [Atomic Red Team t-shirt](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#claim-your-free-t-shirt)

**Review by clr2of8 — APPROVED** [review]

**Comment by collinmsec** [comment]
Thanks!

**Pull request merged**
