### PR TITLE
Added Password Change on Directory Service Restore Mode (DSRM) Account

### PR DESCRIPTION
**Pull request by Rich5**
**Details:**
Added test to reset the DSRM account to mirror to the password of another account. Note that there is no clean-up for this other than the user manually setting the password back. 

**Testing:**
Tested locally.

**Associated Issues:**
N/A

### CODE REVIEW

**Review by clr2of8 — APPROVED** [review]
Looks awesome! Thank you for your first-time contribution. Don't forget to claim your [free t-shirt for being a contributor](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#claim-your-free-t-shirt).

**Comment by clr2of8** [comment]
Congratulations! You've won a $50 gift certificate for the [Black Hills Information Security Store](https://spearphish-general-store.myshopify.com/collections/bhis-shirt-collections) for your contributions to the Atomic Red Team project during the bounty period. Reply to this message with your [Atomic Red Team Slack](https://slack.atomicredteam.io/) username and I (@OrOneEqualsOne) will send you direct message with your coupon code. Thank you for being a part of Atomic Red Team! Keep it up. :)

**Comment by Rich5** [comment]
Oh wow, thanks! My slack username is Rich5

**Comment by clr2of8** [comment]
I'm not seeing any Rich5 in the Atomic Red Team slack. 
image

**Comment by Rich5** [comment]
Oops. Sorry my username is RichK in that one.

**Pull request merged**
