### PR TITLE
Fix typo on T1098.md

### PR DESCRIPTION
**Pull request by za**
Nothing fancy: just fixing a typo.

### CODE REVIEW

**Review by clr2of8 — CHANGES_REQUESTED** [review]
Since the md files are auto-generated from the yaml files of the same, could you update the yaml file instead? Thank you

**Comment by za** [comment]
Noted 📝

**Comment by za** [comment]
Hi @clr2of8 kindly check, I've updated the yaml file.

**Review by clr2of8 — CHANGES_REQUESTED** [review]
I'm sorry, I should have been a little more specific. The only file that needs the update is the https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1098/T1098.yaml file. The yaml Indexes and the mark downs (md) will all be updated automatically. There are some additional notes about it [here](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#make-changes-to-the-repository)

**Comment by za** [comment]
> I'm sorry, I should have been a little more specific. The only file that needs the update is the https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1098/T1098.yaml file. The yaml Indexes and the mark downs (md) will all be updated automatically. There are some additional notes about it [here](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#make-changes-to-the-repository)

Ah, sorry. I miss reading the Contributing notes there.

I've updated the `T1098.yaml` file. Should I revert changes on the other files? @clr2of8

**Comment by za** [comment]
Probably, I'll just create a new PR...

**Review by clr2of8 — APPROVED** [review]
Awesome! Thank you for your first-time contribution. Keep it up! Don't forget to [claim your free Atomic Red Team t-shirt](https://form.asana.com/?k=6EtLaHO7FNHpw1oHrDLJ6g&d=287767067086141)

No need to worry about revoking the other changes and those files will get automatically overwritten

**Pull request merged**
