### PR TITLE
New LocalAdmin Persistence Technique

### PR DESCRIPTION
**Pull request by 0xv1n**
**Details:**
This adds a new test that:
- creates a new local user
- adds that user to local admin group
- deletes the user

**Testing:**
- locally tested on non-domain joined windows 11 device

**Associated Issues:**

### CODE REVIEW

**Comment by 0xv1n** [comment]
There is no `cleanup_command` defined, as the script includes the cleanup:

image

**Review by clr2of8 — DISMISSED** [review]
Thank you! (I updated to use a github permanent link according to the [ontributing guidelines)](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#dependencies)

**Review by clr2of8 — APPROVED** [review]
Thank you!

**Comment by 0xv1n** [comment]
> Thank you! (I updated to use a github permanent link according to the [ontributing guidelines)](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#dependencies)

Thanks Carrie! I'll keep this in mind for the next one <3

**Pull request merged**
