### PR TITLE
Added a new test - XOR Encoded data to T1132.001 'Data Encoding: Standard Encoding

### PR DESCRIPTION
**Pull request by Ayantaker**
Added a new test - XOR Encoded data to T1132.001 'Data Encoding: Standard Encoding

**Details:**
The new test added is for windows powershell. It uses the XOR encoding technique which is a standard encoding technique found in few C2 frameworks. The test is configurable with three parameters - Destination URL, XOR key, Plain text. The XOR logic has been referenced from https://gist.github.com/loadenmb/8254cee0f0287b896a05dcdc8a30042f

**Testing:**
Tested on Powershell version 5.1.19041.610

### CODE REVIEW

**Review by clr2of8 — APPROVED** [review]
Looks great! Thank you for your first-time contribution, keep it up! I updated it slightly to use example.com by default.

**Comment by Ayantaker** [comment]
Hi Carrie, thanks. Really excited to be able to contribute. Had one query since I am a bit new to contributing to open source projects - Will my name show up in the contributors list of the atomic red team or how does it work?

**Comment by clr2of8** [comment]
Congrats, you now show up on the contributors list [here ](https://github.com/redcanaryco/atomic-red-team/graphs/contributors) and can get a free Atomic Red Team t-shirt sent to you by messaging Brian Donohue on the [ Atomic Red Team slack workspace](https://docs.google.com/forms/d/e/1FAIpQLSc3oMtugGy--6kcYiY52ZJQQ-iOaEy-UpxfSA37IlA5wCMV0A/viewform?usp=sf_link).

**Comment by Ayantaker** [comment]
Okay.. Thanks a lot!

**Pull request merged**
