### PR TITLE
T1046 - 

### PR DESCRIPTION
**Pull request by well123cs**
Added test for the containers
Made changes in the yaml file to incorporate containers as platforms

image

image

### CODE REVIEW

**Comment by clr2of8** [comment]
Your description shows only the addition of a test in T1046 but your commit also includes a new test under T1612, is that intentional?

**Comment by well123cs** [comment]
Yes we have added a test to existing T1046 and included a new test under
T1612.

**Comment by patel-bhavin** [comment]
@well123cs : can you please review the conflicts? you had another PR for T1612 which was merged : https://github.com/redcanaryco/atomic-red-team/pull/2375/files

**Comment by well123cs** [comment]
> @well123cs : can you please review the conflicts? you had another PR for T1612 which was merged : https://github.com/redcanaryco/atomic-red-team/pull/2375/files

I have made the necessary changes.
Thanks

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
