### PR TITLE
Test for T1221 Remote Template Injection

### PR DESCRIPTION
**Pull request by mayday-035**
**Details:**
This is adding an atomic for T1221 and providing documents/templates for testing

**Testing:**
Tested in various environment 

**Associated Issues:**
N/A

### CODE REVIEW

**Comment by mayday-035** [comment]
The attached file "Calculator.docx" when opened will load the template "opencalc.dotm"(not attachable) found on my page at:
https://github.com/mayday-035/wrd_template
Once macros are enabled winword will open calc.exe.

[Calculator.docx](https://github.com/redcanaryco/atomic-red-team/files/6303556/Calculator.docx)

**Comment by clr2of8** [comment]
Can you include the Calculator.docx file in the `T1221/src/` directory (called opencalc.dotm I presume since I see that as an input arg) as part of your pull request?

**Comment by mayday-035** [comment]
Should be uploaded, please excuse my lack of understanding this process.  Thanks.

**Review by clr2of8 — APPROVED** [review]
Looks great. Thank you!

**Pull request merged**
