### PR TITLE
New Dump credentials from Windows Credential Manager With PowerShell …

### PR DESCRIPTION
**Pull request by skar4444**
**Details:**
It's possible to dump credentials from Windows Credential Manager(windows Credentials & web Credentials) using PowerShell script

**Testing:**
Tested on windows 10 system without PowerShell administrative access.

### CODE REVIEW

**Review by clr2of8 — CHANGES_REQUESTED** [review]
Thank you for your fist-time contribution, keep up the good work! Just one small change request on this one. Could you refer to the GetCredmanCreds.ps1 using a "permanent link" as described here: https://docs.github.com/en/github/managing-files-in-a-repository/managing-files-on-github/getting-permanent-links-to-files

We like to have permanent links used whenever referring to files in a github repository other than atomic-red-team itself. Thx!

Also, is the script able to extract credential without be run as admin?

**Comment by skar4444** [comment]
Link to the script:
https://github.com/skar4444/Windows-Credential-Manager/blob/main/GetCredmanCreds.ps1

is the script able to extract credential without be run as admin?:: Yes
Thank you for quick response.

**Comment by skar4444** [comment]
Permanent link::
https://github.com/skar4444/Windows-Credential-Manager/blob/4ad208e70c80dd2a9961db40793da291b1981e01/GetCredmanCreds.ps1

**Review by skar4444 — COMMENTED** [review]
changed to permanent link

**Review by skar4444 — COMMENTED** [review]
shared permanent link and script using raw link

**Review by clr2of8 — APPROVED** [review]
Excellent first time contribution, thank you! Keep it up.

**Comment by skar4444** [comment]
Thank you!

**Pull request merged**
