### PR TITLE
T1546.004 Create/Append to .bash_logout

### PR DESCRIPTION
**Pull request by biot-2131**
**Details:**

**Testing:**

**Associated Issues:**

### CODE REVIEW

**Comment by biot-2131** [comment]
Sorry push the button to quickly

Details: 
Added the Create/Append to .bash_logout Atomic...

Testing: 
Tested in VM's and containers: Ubuntu 22.04, ubi8 and rhel 8.7

$ useradd --create-home --shell /bin/bash art
$ su --login art
$ echo 'echo "Atomic Red Team was here... T1546.004" >> $HOME/art.txt' >> $HOME/.bash_logout
$ logout

$ ls -la /home/art/art.txt 
    -rw-rw-r-- 1 art art 40 Feb 17 11:04 /home/art/art.txt
$ cat /home/art/art.txt 
    Atomic Red Team was here... T1546.004

**Comment by biot-2131** [comment]
@josehelps @MSAdministrator Hi guys do you need me to change and resubmit this PR?

**Comment by biot-2131** [comment]
Hi, Ive removed the logout command and the check for the execution of the .bash_logout script.

**Comment by josehelps** [comment]
Perfect thank you so much! Merging.

**Review by josehelps — APPROVED** [review]

**Pull request merged**
