### PR TITLE
Fix Test for T1027.004

### PR DESCRIPTION
**Pull request by iamalsaher**
**Details:**
Updated the input files corresponding to each test to right extension
Changed the executor from powershell to sh

**Testing:**
Tested Locally

**Associated Issues:**
None

### CODE REVIEW

**Review by clr2of8 — CHANGES_REQUESTED** [review]
Thank you for joining us as a first-time contributor! That makes total sense to switch the dependency executor to sh for these linux/macos test. I see you updated the `prereq_command` but we will also need the `get_prereq_command` updated because it is still calling `Invoke-WebRequest` which is a PowerShell command. Maybe switch to curl or wget?

**Comment by iamalsaher** [comment]
Right, I totally forgot, give me 5 mins

**Comment by iamalsaher** [comment]
I believe this should work now

**Review by clr2of8 — APPROVED** [review]
Keep it up! Don't forget to [claim your free t-shirt](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#claim-your-free-t-shirt)

**Pull request merged**
