### PR TITLE
Added Deploying a docker

### PR DESCRIPTION
**Pull request by aman143kri**
Fairly straight forward to deploy a container.

**Details:**
There was no test case for deploying a container in the atomic-red team and I was working with atomic red team so thought to create a pr for this feature

**Testing:**
Tested using ubuntu as the base image. It creates an image and runs that image to check that image is deployed properly.

It may take up to a couple of minutes to run due to image creation. If it hangs for longer than a minute, something went wrong.

**Associated Issues:**
None

### CODE REVIEW

**Comment by aman143kri** [comment]
Execution Screenshot 

image

**Comment by patel-bhavin** [comment]
Same as https://github.com/redcanaryco/atomic-red-team/pull/2254#issuecomment-1363409880.

Thank you!

**Comment by patel-bhavin** [comment]
please rename the src directory as src and NOT Src

**Comment by aman143kri** [comment]
> please rename the src directory as src and NOT Src

Done

**Comment by patel-bhavin** [comment]
Thank you for the updates !

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
