### PR TITLE
New atomics for T1003.003

### PR DESCRIPTION
**Pull request by P4T12ICK**
**Details:**
I added 3 new atomics to technique T1003.003:
- Create Volume Shadow Copy with WMI
- Create Volume Shadow Copy with Powershell
- Create Symlink to Volume Shadow Copy
A lot of my inspiration came from the following slide deck:
https://2017.zeronights.org/wp-content/uploads/materials/ZN17_Kheirkhabarov_Hunting_for_Credentials_Dumping_in_Windows_Environment.pdf

**Testing:**
testing was done with our Attack Range project:
https://github.com/splunk/attack_range

**Associated Issues:**
this PR is not related to an issue

### CODE REVIEW

**Comment by P4T12ICK** [comment]
Hi, thank you for your fast review. I changed it.

**Comment by clr2of8** [comment]
For some reason, Github is telling me "This branch is out-of-date with the base branch" but not giving me the option to update it and therefore I currently can't merge the PR. I'm not sure why this is happening. I'm hoping it resolves itself, but we might have to have you resubmit as a separate PR.

**Comment by P4T12ICK** [comment]
Hi, now it should be okay. Otherwise I can resubmit it. Thank you.

**Comment by clr2of8** [comment]
Still showing "This branch is out-of-date with the base branch" with no option for me to update like there usually is.

**Comment by P4T12ICK** [comment]
I created a new clean PR.

**Pull request closed without merging**
