### PR TITLE
Fix Name and format

### PR DESCRIPTION
**Pull request by 0xzeta**
**Details:**
Fixed format and name

### CODE REVIEW

**Review by clr2of8 — CHANGES_REQUESTED** [review]
Hey Zeta, I appreciated the update to make this test more clear. Could you make this change in the T1592.001.yaml file instead of the markdown file (T1592.001.md) because the markdown files are automatically generated from the yaml files, so if I were to approve this change, your corrections would be immediately overwritten by what is found in the yaml file.

**Comment by clr2of8** [comment]
There are some notes on [the Contributing page](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing) about this that you might find helpful.

**Comment by 0xzeta** [comment]
Fixed Format in T1592.001.yaml

**Review by clr2of8 — APPROVED** [review]

**Comment by clr2of8** [comment]
Thank you for your first-time contribution. Don't forget to claim your [free t-shirt for being a contributor](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#claim-your-free-t-shirt).

**Comment by clr2of8** [comment]
I realized the the Markdown file for this technique wasn't being auto-generated because the filename extension was yml and should have been yaml. I corrected this and now the markdown file is auto-generated from the yaml file. thanks for finding the issue

**Pull request merged**
