### PR TITLE
Another new test: Windows time Command

### PR DESCRIPTION
**Pull request by tropChaud**
Super quick one but recently seen in use in the wild as reported by The DFIR Report

**Testing:**
Successfully tested locally via Invoke-Atomic

### CODE REVIEW

**Review by clr2of8 — CHANGES_REQUESTED** [review]
I like the test and appreciate the inclusion of the links to the blogs in the description. This is really helpful. I just request that you move this new atomic test into [T1124 System Time Discovery](https://attack.mitre.org/techniques/T1124/) instead.

**Review by clr2of8 — APPROVED** [review]

**Review by clr2of8 — CHANGES_REQUESTED** [review]
I like the test and appreciate the inclusion of the links to the blogs in the description. This is really helpful. I just request that you move this new atomic test into [T1124 System Time Discovery](https://attack.mitre.org/techniques/T1124/) instead.

**Comment by clr2of8** [comment]
I like the test and appreciate the inclusion of the links to the blogs in the description. This is really helpful. I just request that you move this new atomic test into [T1124 System Time Discovery](https://attack.mitre.org/techniques/T1124/) instead.

**Comment by tropChaud** [comment]
This totally got away from, making the changeover to T1124 now. Thanks!

**Pull request closed without merging**
