### PR TITLE
Reach out to C2 Pointer URLs via command line

### PR DESCRIPTION
**Pull request by apbeers**
**Details:**
Reach out to C2 Pointer URLs via cmd and PowerShell
Recommended Detection: monitor for a list of these URLs, or a regex that catches web URLs

**Testing:**
Windows 10 VM

### CODE REVIEW

**Comment by ForensicITGuy** [comment]
Hey @apbeers is there a chance you could rework this to use HTTPS requests? As it stands, most bad guys wouldn't be using ICMP to communicate with a web service. HTTPS will more accurately represent real world.

**Comment by apbeers** [comment]
good point. I'll do HTTPS and look into anything else that may make this more accurate

**Comment by apbeers** [comment]
The cleanup commands aren't being run for some reason. Could this be because I just created this folder and it hasn't gone through the circleci build process to generate other files?

**Comment by apbeers** [comment]
@ForensicITGuy can you check out my additions?

**Pull request merged**
