### PR TITLE
T1098 - adding user and service principal to both Azure AD role and Azure role.

### PR DESCRIPTION
**Pull request by WojciechLesicki**
**Details:**
I added four new tests related to Azure - adding user and service principal to both Azure AD role and Azure role.
I followed the example of https://github.com/redcanaryco/atomic-red-team/tree/master/atomics/T1098.001 for consistency, e.g. in the context of connecting via Connect-AzureAD.

I believe that adding users/service principal to roles is an interesting and increasingly developed attack vector. Especially in the context of the service principal itself, which are less known and less used roles such as Privileged authentication administrator.

The materials that inspired me include e.g.
https://posts.specterops.io/azure-privilege-escalation-via-service-principal-abuse-210ae2be2a5

I was wondering if I should post it to https://attack.mitre.org/techniques/T1098/003/, but so far this technique is described as only related to a specific role in Office 365. By the way, I will write to MITER if it is not worth it make changes about T1098.003.

I allowed myself to add detection hint in the description - let me know if you don't mind, but as a defender/ blue team I couldn't resist :)

**Testing:**
Everything tested on my test tenant

### CODE REVIEW

**Comment by WojciechLesicki** [comment]
@patel-bhavin I am wondering if you may need some additional information or something to clarify regarding these atomics.
If I could help somehow - please let me know.

Fyi @clr2of8

**Comment by patel-bhavin** [comment]
@WojciechLesicki : hey, the new atomics looks good! I would let Mitre know of addition you made. Also, since these cloud based atomics are new to the community, the detection hints would be greatly appreciated. Thanks for doing that!

**Review by patel-bhavin — APPROVED** [review]

**Comment by WojciechLesicki** [comment]
@patel-bhavin thanks for the review and merge!
I appreciate the support in the context of MITRE :)

**Comment by MarrelleBailey** [comment]
Congrats on the merge @WojciechLesicki!! You can reach out to me [via Slack](https://slack.atomicredteam.io/) to claim you free Atomic Red Team t-shirt for your first contribution! Also, excited to see you make more contributions! 😃

**Pull request merged**
