### PR TITLE
Tccontre patch 1

### PR DESCRIPTION
**Pull request by tccontre**
**Details:**

nslookup query used by qakbot to discover or gather domain controller information .
**Testing:**

tested manually
**Associated Issues:**

https://securelist.com/qakbot-technical-analysis/103931/

### CODE REVIEW

**Review by clr2of8 — CHANGES_REQUESTED** [review]
Hey there. Thanks for the contribution. I've got a few requests before approval.
1) Can you move this to T1016 instead, since T1033 is about user discovery which is less fitting?
2) for the domain name, can you just use the $env:USERDNSDOMAIN variable? In this case, you likely don't need an input argument. for example `nslookup -querytype=ALL -timeout=12 _ldap._tcp.dc._msdcs.$env:USERDNSDOMAIN`
3) Your nslookup command was missing the `_msdcs` part but I added it above. I also fixed a little typo in the description.

Thanks, Carrie

**Comment by tccontre** [comment]
> Hey there. Thanks for the contribution. I've got a few requests before approval.
> 
> 1. Can you move this to T1016 instead, since T1033 is about user discovery which is less fitting?
> 2. for the domain name, can you just use the $env:USERDNSDOMAIN variable? In this case, you likely don't need an input argument. for example `nslookup -querytype=ALL -timeout=12 _ldap._tcp.dc._msdcs.$env:USERDNSDOMAIN`
> 3. Your nslookup command was missing the `_msdcs` part but I added it above. I also fixed a little typo in the description.
> 
> Thanks, Carrie

thank you Carrie! Ill fix those :)

**Comment by tccontre** [comment]
fix was added thank you again for that great suggestion. :)

**Comment by clr2of8** [comment]
Great! are you able to move the test to T1016 as well?

**Comment by tccontre** [comment]
> Great! are you able to move the test to T1016 as well?

oh sorry I missed that will do. on it now

**Comment by tccontre** [comment]
code move to T1016.

**Review by clr2of8 — APPROVED** [review]
💯

**Pull request merged**
