### PR TITLE
Powershell tactics

### PR DESCRIPTION
**Pull request by tccontre**
**Details:**

atomics for techniques that uses powershell to get the current logged in user and abuses COM object to execute arbitrary or executable file.
**Testing:**

test locally
**Associated Issues:**

### CODE REVIEW

**Review by clr2of8 — CHANGES_REQUESTED** [review]
Hi tccontre, can you provide a link to some more information about your com object atomic that I can review?

Also, you can leaving the auto_generated_guid line out of your PRs completely and one will be auto-assigned when the PR is merged. So unless you like putting your own, you can save yourself a little work there.

**Comment by tccontre** [comment]
thanks @clr2of8 for reminding me i forgot to put some reference link. below is a good reference link for com object attack in powershell I will place it also in the actual atomic. :)

https://pentestlab.blog/2020/05/20/persistence-com-hijacking/

**Review by clr2of8 — APPROVED** [review]
Excellent, thanks. Also, what COM object is represented by that Class ID?

**Comment by tccontre** [comment]
Thank you @clr2of8 ! It is the COM object of ShellWindows.

https://strontic.github.io/xcyclopedia/library/clsid_9BA05972-F6A8-11CF-A442-00A0C90A8F39.html

**Pull request merged**
