### PR TITLE
New Atomic 1219- Splash top Streamer

### PR DESCRIPTION
**Pull request by Pavanrpatil1306**

### CODE REVIEW

**Comment by Pavanrpatil1306** [comment]
description: An adversary may attempt to use Splashtop Streamer to gain unattended remote interactive access. Upon successful execution, Splashtop streamer will be executed.

**Comment by Pavanrpatil1306** [comment]
Working Successfully

**Review by clr2of8 — APPROVED** [review]
Thank you for your first-time contribution. Keep it up! Don't forget to claim your free [Atomic Red Team t-shirt](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#claim-your-free-t-shirt)

**Comment by clr2of8** [comment]
Please resolve the conflict and then I can merge, thank you.

**Pull request closed without merging**
